config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
  	root 'notes#index', as: "authenticated_root"
  end

  root "welcome#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	
	before_action :find_note, only: [:show, :edit, :update, :destroy]
	
	def index
		@notes = Note.where(user_id: current_user)
	end

	def show
	end

	def new
		@note = current_user.notes.build
	end

	def create
		@note = current_user.notes.build(note_params)

		if @note.save
			redirect_to @note
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if  @note.update(note_params)
			redirect_to @note
		else
			render 'edit'
		end
	end

	def destroy
		@note.destroy
		redirect_to notes_path
	end

	private

	def note_params
		params.require(:note).permit(:title, :content)
	end

	def find_note
		@note = Note.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notenote | Your online Notebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
<header>
	<div class="header_inner">
		<%= link_to image_tag('logo.svg'), root_path, id: "logo" %>
		<nav>
			<% if user_signed_in? %>
			<%= link_to "New Note", new_note_path %>
			<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
				<% else %>
			<%= link_to "Log In", new_user_session_path %>
			<% end %>
		</nav>
	</div>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <br>
  <div class="action">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="wrapper_with_padding">
	<h1>Edit Note
	</h1>
	<%= render 'form' %>
	<%= link_to "Cancel", note_path %>
</div>

app/views/notes/index.html.erb
<div class="wrapper_with_padding">
	<div class="clearfix" id="notes">
		<% unless @notes.blank? %>
			<% @notes.each do |note| %>
        <a href="<%= (url_for [note]) %>">
          <div class="note">
            <p class="title">
              <%= note.title %>
            </p>
            <p class="date">
              <%= time_ago_in_words(note.created_at) %>
            </p>
          </div>
        </a>
      <% end %>
    <% else %>
      <h2>Add a Note</h2>
      <p>It appears you haven't created any notes yet... Lets fix that. Why don't you go ahead and create a new note.</p>
      <button>
        <%= link_to "New Note", new_note_path %>
      </button>
    <% end %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="wrapper_with_padding">
	<h1>Add a note</h1>
	<%= render 'form' %>
</div>

app/views/notes/show.html.erb
<div class="wrapper_with_padding">
	<div id="note_show">
		<h1 class="title">
			<%= @note.title %>
		</h1>
		<p>
			<%= simple_format(@note.content) %>
		</p>
		<div class="buttons">
			<%= link_to "Edit", edit_note_path(@note), class: "button" %>
			<%= link_to "Delete", note_path(@note), class: "button", method: :delete, data: { confirm: "Are you sure?" } %>		
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div id="banner">
	<div class="banner_content">
		<h1>NoteNote</h1>
			<p>Your online notebook, Never forget and idea again</p>
			<button>
				<%= link_to "Sign Up", new_user_registration_path %>
			</button>
	</div>
</div>

<div id="testimonial">
	<div class="wrapper">
		<p class="quote">The greatest notebook application. Period.</p>
		<p class="name">Pabst Blue Ribbon</p>
	</div>
</div>

<div id="callouts">
	<div class="callout_inner">
		<div class="wrapper">
			<div class="callout">
			<i class="fa fa-pencil"></i>
				<h2>Notes</h2>
				<p>Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.</p>
			</div>
			<div class="callout">
			<i class="fa fa-rocket"></i>
				<h2>Rocket</h2>
				<p>Quinoa Austin craft beer distillery pour-over small batch, mlkshk cold-pressed cred umami twee church-key. Church-key fanny pack cold-pressed drinking vinegar.</p>
			</div>
			<div class="callout">
			<i class="fa fa-wrench"></i>
				<h2>Wrench</h2>
				<p>Art party pug fap pop-up literally skateboard. Four loko banjo bicycle rights, cold-pressed synth vegan try-hard paleo bitters ethical wayfarers distillery. Lumbersexual slow-carb plaid PBR&B. </p>
			</div>
		</div>
	</div>
</div>

<div id="bottom_cta">
	<div class="wrapper">
		<h2>For realz!</h2>
		<p>I want you to sign up....If you don't I will find you!</p>
		<button><%= link_to "Click Me!", new_user_registration_path %></button>
	</div>
</div>

<footer>
	<p>&copy; Chris Mangano</p>
</footer>